application: sillyswarm
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.jar$

handlers:

- url: /sillyswarm/(.*\.(js))
  static_files: js/\1
  upload: js/(.*\.(js))
  expiration: 5h

- url: /sillyswarm/(.*\.(gif|jpg|png))
  static_files: images/\1
  upload: images/(.*\.(gif|jpg|png))
  expiration: 5h

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /_ah/websocket/.*
  script: app.py
  login: admin

- url: /.*
  script: app.py
